// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsyFaXCw1S9pFeZlTH8qxj1Go52LrQSxU',
    appId: '1:330593564199:web:fe72258e3fc4defeda4002',
    messagingSenderId: '330593564199',
    projectId: 'eventsappauth-60f5f',
    authDomain: 'eventsappauth-60f5f.firebaseapp.com',
    storageBucket: 'eventsappauth-60f5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoy0pB4Zd7dE2en5-qvj0TNjLElUx2KHU',
    appId: '1:330593564199:android:164189dd8437f047da4002',
    messagingSenderId: '330593564199',
    projectId: 'eventsappauth-60f5f',
    storageBucket: 'eventsappauth-60f5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYqfli2pVqLytxPY95mDGrQ3KoQn2obnU',
    appId: '1:330593564199:ios:0227c2c4bc4cd4acda4002',
    messagingSenderId: '330593564199',
    projectId: 'eventsappauth-60f5f',
    storageBucket: 'eventsappauth-60f5f.appspot.com',
    iosBundleId: 'com.example.eventsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYqfli2pVqLytxPY95mDGrQ3KoQn2obnU',
    appId: '1:330593564199:ios:cea0b58e5de0dfeeda4002',
    messagingSenderId: '330593564199',
    projectId: 'eventsappauth-60f5f',
    storageBucket: 'eventsappauth-60f5f.appspot.com',
    iosBundleId: 'com.example.eventsApp.RunnerTests',
  );
}
